algo = input('Digite algo: ')
print('A variavel "{}" é do tipo:'.format(algo), type(algo))
print('É letra? ', algo.isalpha())
print('É número? ', algo.isnumeric())
print('É letra e número? ', algo.isalnum())
print('É decimal? ', algo.isdecimal())
print('Tem espaço? ', algo.isspace())
print('Tem maiúsculas? ', algo.isupper())
print('Tem minúsculas? ', algo.islower())